/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio y de su base de datos */
        get: operations["leer_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login con email y password. Devuelve access + refresh. */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rota el refresh y devuelve un access nuevo. */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalida el refresh rotandolo a NULL. */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el usuario autenticado. Solo para smoke-test del token. */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sueno": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra el sueño del día. Upsert por fecha. */
        post: operations["registrar_sueno_api_v1_sueno_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sueno/{fecha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el registro de sueño de una fecha. */
        get: operations["leer_sueno_api_v1_sueno__fecha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bienestar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra el bienestar del día (índice de Hooper). Upsert por fecha. */
        post: operations["registrar_bienestar_api_v1_bienestar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bienestar/{fecha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el registro de bienestar de una fecha. */
        get: operations["leer_bienestar_api_v1_bienestar__fecha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habitos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los hábitos activos del usuario. */
        get: operations["listar_habitos_api_v1_habitos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habitos/registro/{fecha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los hábitos ya registrados en una fecha. */
        get: operations["leer_registros_api_v1_habitos_registro__fecha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habitos/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca un hábito para una fecha. Upsert por (habito_id, fecha). */
        post: operations["registrar_habito_api_v1_habitos_registro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HabitoRead */
        HabitoRead: {
            /** Id */
            id: number;
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /** Nombre */
            nombre: string;
            /** Activo */
            activo: boolean;
            /** Orden */
            orden: number;
        };
        /** HabitoRegistroCreate */
        HabitoRegistroCreate: {
            /** Habito Id */
            habito_id: number;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Valor */
            valor: boolean;
        };
        /** HabitoRegistroRead */
        HabitoRegistroRead: {
            /** Habito Id */
            habito_id: number;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Valor */
            valor: boolean;
        };
        /** HealthRead */
        HealthRead: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Base De Datos
             * @enum {string}
             */
            base_de_datos: "ok" | "sin_conexion";
        };
        /**
         * LoginRequest
         * @description Email + password. La unicidad del email esta en la DB; el formato
         *     lo valida Pydantic aca para devolver 422 con mensaje util en vez de
         *     un error de integridad.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OrigenDato
         * @enum {string}
         */
        OrigenDato: "manual" | "health_kit" | "notion_backfill";
        /**
         * RefreshRequest
         * @description El refresh token es opaco: el cliente lo manda tal cual lo recibio,
         *     sin transformarlo. El server lo hashea y busca por hash.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegistroBienestarCreate
         * @description Los cuatro ítems del Hooper. En los cuatro, 1 es bueno y 5 es malo.
         */
        RegistroBienestarCreate: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Sueno Pobre */
            sueno_pobre: number;
            /** Fatiga */
            fatiga: number;
            /** Dolor Muscular */
            dolor_muscular: number;
            /** Estres */
            estres: number;
        };
        /** RegistroBienestarRead */
        RegistroBienestarRead: {
            /** Id */
            id: number;
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Sueno Pobre */
            sueno_pobre: number;
            /** Fatiga */
            fatiga: number;
            /** Dolor Muscular */
            dolor_muscular: number;
            /** Estres */
            estres: number;
            /** Hooper */
            hooper: number;
        };
        /**
         * RegistroSuenoCreate
         * @description `usuario_id` no viaja en el cuerpo: sale del usuario autenticado.
         */
        RegistroSuenoCreate: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fin
             * Format: date-time
             */
            fin: string;
            /** Celular Fuera */
            celular_fuera?: boolean | null;
            /** @default manual */
            origen: components["schemas"]["OrigenDato"];
        };
        /** RegistroSuenoRead */
        RegistroSuenoRead: {
            /** Id */
            id: number;
            /**
             * Usuario Id
             * Format: uuid
             */
            usuario_id: string;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fin
             * Format: date-time
             */
            fin: string;
            /** Celular Fuera */
            celular_fuera: boolean | null;
            origen: components["schemas"]["OrigenDato"];
            /** Horas Sueno */
            horas_sueno: string;
        };
        /**
         * TokenResponse
         * @description Respuesta de login y refresh. `expires_in` es en segundos (900 = 15 min)
         *     para que el cliente pueda programar la renovacion sin parsear el JWT.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    leer_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    registrar_sueno_api_v1_sueno_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroSuenoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroSuenoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leer_sueno_api_v1_sueno__fecha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fecha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroSuenoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_bienestar_api_v1_bienestar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroBienestarCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroBienestarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leer_bienestar_api_v1_bienestar__fecha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fecha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroBienestarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_habitos_api_v1_habitos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitoRead"][];
                };
            };
        };
    };
    leer_registros_api_v1_habitos_registro__fecha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fecha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitoRegistroRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_habito_api_v1_habitos_registro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitoRegistroCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitoRegistroRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
