"""agregar tablas de nutricion (fase 6)

Revision ID: 1f411c7f0bca
Revises: 772c63592825
Create Date: 2026-08-07 10:17:53.641695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1f411c7f0bca"
down_revision: str | None = "772c63592825"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alimento",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column(
            "grupo",
            sa.Enum(
                "proteina_animal",
                "lacteo",
                "cereal",
                "leguminosa",
                "tuberculo",
                "verdura",
                "fruta",
                "grasa",
                "procesado",
                name="grupo_alimento",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado_pesaje",
            sa.Enum("crudo", "cocido", name="estado_pesaje"),
            server_default="crudo",
            nullable=False,
        ),
        sa.Column("kcal_100g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("proteina_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("carbo_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("grasa_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("fibra_100g", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fuente", sa.String(length=60), nullable=True),
        sa.CheckConstraint(
            "carbo_100g >= 0", name=op.f("ck_alimento_carbo_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "fibra_100g >= 0", name=op.f("ck_alimento_fibra_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "grasa_100g >= 0", name=op.f("ck_alimento_grasa_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "kcal_100g >= 0", name=op.f("ck_alimento_kcal_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "proteina_100g >= 0", name=op.f("ck_alimento_proteina_100g_no_negativo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alimento")),
        sa.UniqueConstraint("nombre", name=op.f("uq_alimento_nombre")),
    )
    op.create_table(
        "despensa",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column(
            "imprescindible", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("en_stock", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_despensa_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_despensa_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("usuario_id", "alimento_id", name=op.f("pk_despensa")),
    )
    op.create_table(
        "receta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column(
            "momento_default",
            sa.Enum(
                "desayuno",
                "media_manana",
                "almuerzo",
                "merienda",
                "cena",
                name="momento_comida",
            ),
            nullable=True,
        ),
        sa.Column("activa", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_receta_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receta")),
        sa.UniqueConstraint(
            "usuario_id", "nombre", name=op.f("uq_receta_usuario_id_nombre")
        ),
    )
    op.create_table(
        "comida_log",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "momento",
            sa.Enum(
                "desayuno",
                "media_manana",
                "almuerzo",
                "merienda",
                "cena",
                name="momento_comida",
            ),
            nullable=False,
        ),
        sa.Column("receta_id", sa.Integer(), nullable=True),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receta_id"], ["receta.id"], name=op.f("fk_comida_log_receta_id_receta")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_comida_log_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comida_log")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_comida_log_idempotency_key")
        ),
    )
    op.create_index(
        "ix_comida_log_usuario_id_fecha_momento",
        "comida_log",
        ["usuario_id", "fecha", "momento"],
        unique=False,
    )
    op.create_table(
        "receta_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("receta_id", sa.Integer(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column("cantidad_g", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.CheckConstraint(
            "cantidad_g > 0", name=op.f("ck_receta_item_cantidad_g_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_receta_item_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["receta_id"], ["receta.id"], name=op.f("fk_receta_item_receta_id_receta")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receta_item")),
        sa.UniqueConstraint(
            "receta_id",
            "alimento_id",
            name=op.f("uq_receta_item_receta_id_alimento_id"),
        ),
    )
    op.create_table(
        "comida_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("comida_log_id", sa.Uuid(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column("cantidad_g", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.CheckConstraint(
            "cantidad_g > 0", name=op.f("ck_comida_item_cantidad_g_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_comida_item_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["comida_log_id"],
            ["comida_log.id"],
            name=op.f("fk_comida_item_comida_log_id_comida_log"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comida_item")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comida_item")
    op.drop_table("receta_item")
    op.drop_index("ix_comida_log_usuario_id_fecha_momento", table_name="comida_log")
    op.drop_table("comida_log")
    op.drop_table("receta")
    op.drop_table("despensa")
    op.drop_table("alimento")
    # ### end Alembic commands ###
