"""agregar registro_hidratacion y meta de agua

Revision ID: 62737111fe81
Revises: b2dc6e2c7f8b
Create Date: 2026-08-05 18:40:14.512690

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "62737111fe81"
down_revision: str | None = "b2dc6e2c7f8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registro_hidratacion",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "ml_totales", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.CheckConstraint(
            "ml_totales >= 0",
            name=op.f("ck_registro_hidratacion_ml_totales_no_negativos"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_registro_hidratacion_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registro_hidratacion")),
        sa.UniqueConstraint(
            "usuario_id", "fecha", name=op.f("uq_registro_hidratacion_usuario_id_fecha")
        ),
    )
    op.add_column(
        "usuario", sa.Column("agua_objetivo_ml_min", sa.Integer(), nullable=True)
    )
    op.add_column(
        "usuario", sa.Column("agua_objetivo_ml_max", sa.Integer(), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_usuario_agua_objetivo_ml_ordenado"),
        "usuario",
        "agua_objetivo_ml_min IS NULL OR agua_objetivo_ml_max IS NULL OR agua_objetivo_ml_min <= agua_objetivo_ml_max",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_usuario_agua_objetivo_ml_ordenado"), "usuario", type_="check"
    )
    op.drop_column("usuario", "agua_objetivo_ml_max")
    op.drop_column("usuario", "agua_objetivo_ml_min")
    op.drop_table("registro_hidratacion")
    # ### end Alembic commands ###
