"""agregar ciclo_semana_composicion, fecha fin/cierre de ciclo y dia sugerido

Revision ID: 844c752ec28c
Revises: 62737111fe81
Create Date: 2026-08-05 23:54:13.142742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "844c752ec28c"
down_revision: str | None = "62737111fe81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ciclo_semana_composicion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ciclo_semana_id", sa.Integer(), nullable=False),
        sa.Column("tipo_sesion_id", sa.SmallInteger(), nullable=False),
        sa.Column("cantidad_objetivo", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "cantidad_objetivo > 0",
            name=op.f("ck_ciclo_semana_composicion_cantidad_objetivo_positiva"),
        ),
        sa.ForeignKeyConstraint(
            ["ciclo_semana_id"],
            ["ciclo_semana.id"],
            name=op.f("fk_ciclo_semana_composicion_ciclo_semana_id_ciclo_semana"),
        ),
        sa.ForeignKeyConstraint(
            ["tipo_sesion_id"],
            ["tipo_sesion.id"],
            name=op.f("fk_ciclo_semana_composicion_tipo_sesion_id_tipo_sesion"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ciclo_semana_composicion")),
        sa.UniqueConstraint(
            "ciclo_semana_id",
            "tipo_sesion_id",
            name=op.f("uq_ciclo_semana_composicion_ciclo_semana_id_tipo_sesion_id"),
        ),
    )
    op.add_column(
        "ciclo",
        sa.Column(
            "fecha_fin_prevista",
            sa.Date(),
            sa.Computed("fecha_inicio + (semanas * 7 - 1)", persisted=True),
            nullable=False,
        ),
    )
    op.add_column("ciclo", sa.Column("fecha_cierre_real", sa.Date(), nullable=True))
    op.create_check_constraint(
        op.f("ck_ciclo_fecha_cierre_coherente"),
        "ciclo",
        "fecha_cierre_real IS NULL OR estado = 'cerrado'",
    )
    op.add_column(
        "sesion_plan", sa.Column("dia_sugerido", sa.SmallInteger(), nullable=True)
    )
    op.alter_column(
        "sesion_plan", "fecha_prevista", existing_type=sa.DATE(), nullable=True
    )
    op.create_check_constraint(
        op.f("ck_sesion_plan_dia_sugerido_rango"),
        "sesion_plan",
        "dia_sugerido IS NULL OR dia_sugerido BETWEEN 0 AND 6",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_sesion_plan_dia_sugerido_rango"), "sesion_plan", type_="check"
    )
    op.alter_column(
        "sesion_plan", "fecha_prevista", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("sesion_plan", "dia_sugerido")
    op.drop_constraint(op.f("ck_ciclo_fecha_cierre_coherente"), "ciclo", type_="check")
    op.drop_column("ciclo", "fecha_cierre_real")
    op.drop_column("ciclo", "fecha_fin_prevista")
    op.drop_table("ciclo_semana_composicion")
    # ### end Alembic commands ###
