"""esquema inicial

Revision ID: a1b113ff814a
Revises:
Create Date: 2026-08-04 23:41:47.522509

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b113ff814a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alimento",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column(
            "grupo",
            sa.Enum(
                "proteina_animal",
                "lacteo",
                "cereal",
                "leguminosa",
                "tuberculo",
                "verdura",
                "fruta",
                "grasa",
                "procesado",
                name="grupo_alimento",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado_pesaje",
            sa.Enum("crudo", "cocido", name="estado_pesaje"),
            server_default="crudo",
            nullable=False,
        ),
        sa.Column("kcal_100g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("proteina_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("carbo_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("grasa_100g", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("fibra_100g", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fuente", sa.String(length=60), nullable=True),
        sa.CheckConstraint(
            "carbo_100g >= 0", name=op.f("ck_alimento_carbo_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "fibra_100g >= 0", name=op.f("ck_alimento_fibra_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "grasa_100g >= 0", name=op.f("ck_alimento_grasa_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "kcal_100g >= 0", name=op.f("ck_alimento_kcal_100g_no_negativo")
        ),
        sa.CheckConstraint(
            "proteina_100g >= 0", name=op.f("ck_alimento_proteina_100g_no_negativo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alimento")),
        sa.UniqueConstraint("nombre", name=op.f("uq_alimento_nombre")),
    )
    op.create_table(
        "ejercicio",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("patron", sa.String(length=40), nullable=True),
        sa.Column(
            "carga_lumbar",
            sa.Enum("alta", "media", "baja", name="carga_lumbar"),
            server_default="baja",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ejercicio")),
        sa.UniqueConstraint("nombre", name=op.f("uq_ejercicio_nombre")),
    )
    op.create_table(
        "parametro",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column("valor", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("unidad", sa.String(length=20), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "vigente_desde",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parametro")),
        sa.UniqueConstraint(
            "clave", "vigente_desde", name=op.f("uq_parametro_clave_vigente_desde")
        ),
    )
    op.create_table(
        "tipo_sesion",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column(
            "demanda", sa.Enum("alta", "media", "baja", name="demanda"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tipo_sesion")),
        sa.UniqueConstraint("codigo", name=op.f("uq_tipo_sesion_codigo")),
    )
    op.create_table(
        "tipo_test",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("unidad", sa.String(length=10), nullable=False),
        sa.Column("mejor_es_mayor", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tipo_test")),
        sa.UniqueConstraint("codigo", name=op.f("uq_tipo_test_codigo")),
    )
    op.create_table(
        "usuario",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("peso_objetivo_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
    )
    op.create_table(
        "zona_corporal",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zona_corporal")),
        sa.UniqueConstraint("nombre", name=op.f("uq_zona_corporal_nombre")),
    )
    op.create_table(
        "ciclo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("numero", sa.SmallInteger(), nullable=False),
        sa.Column("objetivo", sa.Text(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("semanas", sa.SmallInteger(), server_default="4", nullable=False),
        sa.Column(
            "estado",
            sa.Enum("planificado", "activo", "cerrado", name="estado_ciclo"),
            server_default="planificado",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_ciclo_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ciclo")),
        sa.UniqueConstraint(
            "usuario_id", "numero", name=op.f("uq_ciclo_usuario_id_numero")
        ),
    )
    op.create_table(
        "despensa",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column(
            "imprescindible", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("en_stock", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_despensa_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_despensa_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("usuario_id", "alimento_id", name=op.f("pk_despensa")),
    )
    op.create_table(
        "habito",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("orden", sa.SmallInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_habito_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habito")),
        sa.UniqueConstraint(
            "usuario_id", "nombre", name=op.f("uq_habito_usuario_id_nombre")
        ),
    )
    op.create_table(
        "medida_corporal",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("peso_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("fc_reposo", sa.SmallInteger(), nullable=True),
        sa.Column(
            "origen",
            sa.Enum("manual", "health_kit", "notion_backfill", name="origen_dato"),
            server_default="manual",
            nullable=False,
        ),
        sa.CheckConstraint(
            "fc_reposo IS NULL OR fc_reposo > 0",
            name=op.f("ck_medida_corporal_fc_reposo_positiva"),
        ),
        sa.CheckConstraint(
            "peso_kg > 0", name=op.f("ck_medida_corporal_peso_kg_positivo")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_medida_corporal_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medida_corporal")),
        sa.UniqueConstraint(
            "usuario_id", "fecha", name=op.f("uq_medida_corporal_usuario_id_fecha")
        ),
    )
    op.create_table(
        "molestia",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("zona_id", sa.SmallInteger(), nullable=False),
        sa.Column("intensidad", sa.SmallInteger(), nullable=False),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "intensidad BETWEEN 1 AND 10", name=op.f("ck_molestia_intensidad_rango")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_molestia_usuario_id_usuario")
        ),
        sa.ForeignKeyConstraint(
            ["zona_id"],
            ["zona_corporal.id"],
            name=op.f("fk_molestia_zona_id_zona_corporal"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_molestia")),
        sa.UniqueConstraint(
            "usuario_id",
            "fecha",
            "zona_id",
            name=op.f("uq_molestia_usuario_id_fecha_zona_id"),
        ),
    )
    op.create_index(
        "ix_molestia_usuario_id_zona_id_fecha",
        "molestia",
        ["usuario_id", "zona_id", "fecha"],
        unique=False,
    )
    op.create_table(
        "receta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column(
            "momento_default",
            sa.Enum(
                "desayuno",
                "media_manana",
                "almuerzo",
                "merienda",
                "cena",
                name="momento_comida",
            ),
            nullable=True,
        ),
        sa.Column("activa", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_receta_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receta")),
        sa.UniqueConstraint(
            "usuario_id", "nombre", name=op.f("uq_receta_usuario_id_nombre")
        ),
    )
    op.create_table(
        "registro_bienestar",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("sueno_pobre", sa.SmallInteger(), nullable=False),
        sa.Column("fatiga", sa.SmallInteger(), nullable=False),
        sa.Column("dolor_muscular", sa.SmallInteger(), nullable=False),
        sa.Column("estres", sa.SmallInteger(), nullable=False),
        sa.Column(
            "hooper",
            sa.SmallInteger(),
            sa.Computed(
                "sueno_pobre + fatiga + dolor_muscular + estres", persisted=True
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dolor_muscular BETWEEN 1 AND 5",
            name=op.f("ck_registro_bienestar_dolor_muscular_rango"),
        ),
        sa.CheckConstraint(
            "estres BETWEEN 1 AND 5", name=op.f("ck_registro_bienestar_estres_rango")
        ),
        sa.CheckConstraint(
            "fatiga BETWEEN 1 AND 5", name=op.f("ck_registro_bienestar_fatiga_rango")
        ),
        sa.CheckConstraint(
            "sueno_pobre BETWEEN 1 AND 5",
            name=op.f("ck_registro_bienestar_sueno_pobre_rango"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_registro_bienestar_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registro_bienestar")),
        sa.UniqueConstraint(
            "usuario_id", "fecha", name=op.f("uq_registro_bienestar_usuario_id_fecha")
        ),
    )
    op.create_table(
        "registro_sueno",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("celular_fuera", sa.Boolean(), nullable=True),
        sa.Column(
            "origen",
            sa.Enum("manual", "health_kit", "notion_backfill", name="origen_dato"),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "horas_sueno",
            sa.Numeric(precision=4, scale=2),
            sa.Computed("EXTRACT(EPOCH FROM (fin - inicio)) / 3600.0", persisted=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fin > inicio", name=op.f("ck_registro_sueno_fin_posterior_a_inicio")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_registro_sueno_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registro_sueno")),
        sa.UniqueConstraint(
            "usuario_id", "fecha", name=op.f("uq_registro_sueno_usuario_id_fecha")
        ),
    )
    op.create_table(
        "test_fisico",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("tipo_test_id", sa.SmallInteger(), nullable=False),
        sa.Column("superficie", sa.String(length=40), nullable=True),
        sa.Column("condiciones", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tipo_test_id"],
            ["tipo_test.id"],
            name=op.f("fk_test_fisico_tipo_test_id_tipo_test"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_test_fisico_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_fisico")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_test_fisico_idempotency_key")
        ),
    )
    op.create_index(
        "ix_test_fisico_usuario_id_tipo_test_id_fecha",
        "test_fisico",
        ["usuario_id", "tipo_test_id", "fecha"],
        unique=False,
    )
    op.create_table(
        "ciclo_semana",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ciclo_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.SmallInteger(), nullable=False),
        sa.Column(
            "fase",
            sa.Enum("readaptacion", "carga", "descarga", name="fase_ciclo"),
            nullable=False,
        ),
        sa.Column("rpe_objetivo_min", sa.SmallInteger(), nullable=True),
        sa.Column("rpe_objetivo_max", sa.SmallInteger(), nullable=True),
        sa.Column(
            "volumen_pct", sa.SmallInteger(), server_default="100", nullable=False
        ),
        sa.CheckConstraint(
            "rpe_objetivo_max IS NULL OR rpe_objetivo_max BETWEEN 1 AND 10",
            name=op.f("ck_ciclo_semana_rpe_objetivo_max_rango"),
        ),
        sa.CheckConstraint(
            "rpe_objetivo_min IS NULL OR rpe_objetivo_max IS NULL OR rpe_objetivo_min <= rpe_objetivo_max",
            name=op.f("ck_ciclo_semana_rpe_objetivo_ordenado"),
        ),
        sa.CheckConstraint(
            "rpe_objetivo_min IS NULL OR rpe_objetivo_min BETWEEN 1 AND 10",
            name=op.f("ck_ciclo_semana_rpe_objetivo_min_rango"),
        ),
        sa.ForeignKeyConstraint(
            ["ciclo_id"], ["ciclo.id"], name=op.f("fk_ciclo_semana_ciclo_id_ciclo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ciclo_semana")),
        sa.UniqueConstraint(
            "ciclo_id", "numero", name=op.f("uq_ciclo_semana_ciclo_id_numero")
        ),
    )
    op.create_table(
        "comida_log",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "momento",
            sa.Enum(
                "desayuno",
                "media_manana",
                "almuerzo",
                "merienda",
                "cena",
                name="momento_comida",
            ),
            nullable=False,
        ),
        sa.Column("receta_id", sa.Integer(), nullable=True),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receta_id"], ["receta.id"], name=op.f("fk_comida_log_receta_id_receta")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_comida_log_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comida_log")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_comida_log_idempotency_key")
        ),
    )
    op.create_index(
        "ix_comida_log_usuario_id_fecha_momento",
        "comida_log",
        ["usuario_id", "fecha", "momento"],
        unique=False,
    )
    op.create_table(
        "habito_registro",
        sa.Column("habito_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("valor", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habito_id"],
            ["habito.id"],
            name=op.f("fk_habito_registro_habito_id_habito"),
        ),
        sa.PrimaryKeyConstraint("habito_id", "fecha", name=op.f("pk_habito_registro")),
    )
    op.create_table(
        "receta_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("receta_id", sa.Integer(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column("cantidad_g", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.CheckConstraint(
            "cantidad_g > 0", name=op.f("ck_receta_item_cantidad_g_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_receta_item_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["receta_id"], ["receta.id"], name=op.f("fk_receta_item_receta_id_receta")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receta_item")),
        sa.UniqueConstraint(
            "receta_id",
            "alimento_id",
            name=op.f("uq_receta_item_receta_id_alimento_id"),
        ),
    )
    op.create_table(
        "test_intento",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("test_fisico_id", sa.Uuid(), nullable=False),
        sa.Column("numero", sa.SmallInteger(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.CheckConstraint("numero > 0", name=op.f("ck_test_intento_numero_positivo")),
        sa.CheckConstraint("valor > 0", name=op.f("ck_test_intento_valor_positivo")),
        sa.ForeignKeyConstraint(
            ["test_fisico_id"],
            ["test_fisico.id"],
            name=op.f("fk_test_intento_test_fisico_id_test_fisico"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_intento")),
        sa.UniqueConstraint(
            "test_fisico_id",
            "numero",
            name=op.f("uq_test_intento_test_fisico_id_numero"),
        ),
    )
    op.create_table(
        "comida_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("comida_log_id", sa.Uuid(), nullable=False),
        sa.Column("alimento_id", sa.Integer(), nullable=False),
        sa.Column("cantidad_g", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.CheckConstraint(
            "cantidad_g > 0", name=op.f("ck_comida_item_cantidad_g_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["alimento_id"],
            ["alimento.id"],
            name=op.f("fk_comida_item_alimento_id_alimento"),
        ),
        sa.ForeignKeyConstraint(
            ["comida_log_id"],
            ["comida_log.id"],
            name=op.f("fk_comida_item_comida_log_id_comida_log"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comida_item")),
    )
    op.create_table(
        "sesion_plan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("ciclo_semana_id", sa.Integer(), nullable=True),
        sa.Column("fecha_prevista", sa.Date(), nullable=False),
        sa.Column("tipo_sesion_id", sa.SmallInteger(), nullable=False),
        sa.Column("objetivo", sa.Text(), nullable=True),
        sa.Column("duracion_min_est", sa.SmallInteger(), nullable=True),
        sa.Column("rpe_objetivo", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "duracion_min_est IS NULL OR duracion_min_est > 0",
            name=op.f("ck_sesion_plan_duracion_min_est_positiva"),
        ),
        sa.CheckConstraint(
            "rpe_objetivo IS NULL OR rpe_objetivo BETWEEN 1 AND 10",
            name=op.f("ck_sesion_plan_rpe_objetivo_rango"),
        ),
        sa.ForeignKeyConstraint(
            ["ciclo_semana_id"],
            ["ciclo_semana.id"],
            name=op.f("fk_sesion_plan_ciclo_semana_id_ciclo_semana"),
        ),
        sa.ForeignKeyConstraint(
            ["tipo_sesion_id"],
            ["tipo_sesion.id"],
            name=op.f("fk_sesion_plan_tipo_sesion_id_tipo_sesion"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_sesion_plan_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesion_plan")),
    )
    op.create_table(
        "serie_plan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sesion_plan_id", sa.Integer(), nullable=False),
        sa.Column("ejercicio_id", sa.Integer(), nullable=False),
        sa.Column("orden", sa.SmallInteger(), nullable=False),
        sa.Column("series", sa.SmallInteger(), nullable=False),
        sa.Column("reps_min", sa.SmallInteger(), nullable=True),
        sa.Column("reps_max", sa.SmallInteger(), nullable=True),
        sa.Column("peso_objetivo_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.CheckConstraint(
            "reps_min IS NULL OR reps_max IS NULL OR reps_min <= reps_max",
            name=op.f("ck_serie_plan_reps_ordenadas"),
        ),
        sa.CheckConstraint("series > 0", name=op.f("ck_serie_plan_series_positivas")),
        sa.ForeignKeyConstraint(
            ["ejercicio_id"],
            ["ejercicio.id"],
            name=op.f("fk_serie_plan_ejercicio_id_ejercicio"),
        ),
        sa.ForeignKeyConstraint(
            ["sesion_plan_id"],
            ["sesion_plan.id"],
            name=op.f("fk_serie_plan_sesion_plan_id_sesion_plan"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_serie_plan")),
        sa.UniqueConstraint(
            "sesion_plan_id", "orden", name=op.f("uq_serie_plan_sesion_plan_id_orden")
        ),
    )
    op.create_table(
        "sesion",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("sesion_plan_id", sa.Integer(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("tipo_sesion_id", sa.SmallInteger(), nullable=False),
        sa.Column("duracion_min", sa.SmallInteger(), nullable=False),
        sa.Column("rpe", sa.SmallInteger(), nullable=False),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column(
            "carga_srpe",
            sa.Integer(),
            sa.Computed("rpe * duracion_min", persisted=True),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column(
            "registrado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duracion_min > 0", name=op.f("ck_sesion_duracion_min_positiva")
        ),
        sa.CheckConstraint("rpe BETWEEN 1 AND 10", name=op.f("ck_sesion_rpe_rango")),
        sa.ForeignKeyConstraint(
            ["sesion_plan_id"],
            ["sesion_plan.id"],
            name=op.f("fk_sesion_sesion_plan_id_sesion_plan"),
        ),
        sa.ForeignKeyConstraint(
            ["tipo_sesion_id"],
            ["tipo_sesion.id"],
            name=op.f("fk_sesion_tipo_sesion_id_tipo_sesion"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_sesion_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesion")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_sesion_idempotency_key")),
        sa.UniqueConstraint("sesion_plan_id", name=op.f("uq_sesion_sesion_plan_id")),
    )
    op.create_index(
        "ix_sesion_usuario_id_fecha", "sesion", ["usuario_id", "fecha"], unique=False
    )
    op.create_table(
        "partido",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("sesion_id", sa.Uuid(), nullable=False),
        sa.Column("rival", sa.String(length=80), nullable=True),
        sa.Column("formato", sa.String(length=20), nullable=True),
        sa.Column("minutos_jugados", sa.SmallInteger(), nullable=False),
        sa.Column("goles", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("asistencias", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("recuperaciones", sa.SmallInteger(), nullable=True),
        sa.Column("salio_bien", sa.Text(), nullable=True),
        sa.Column("a_ajustar", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "asistencias >= 0", name=op.f("ck_partido_asistencias_no_negativas")
        ),
        sa.CheckConstraint("goles >= 0", name=op.f("ck_partido_goles_no_negativos")),
        sa.CheckConstraint(
            "minutos_jugados >= 0", name=op.f("ck_partido_minutos_jugados_no_negativos")
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"], ["sesion.id"], name=op.f("fk_partido_sesion_id_sesion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partido")),
        sa.UniqueConstraint("sesion_id", name=op.f("uq_partido_sesion_id")),
    )
    op.create_table(
        "serie",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sesion_id", sa.Uuid(), nullable=False),
        sa.Column("ejercicio_id", sa.Integer(), nullable=False),
        sa.Column("orden", sa.SmallInteger(), nullable=False),
        sa.Column("series", sa.SmallInteger(), nullable=False),
        sa.Column("reps", sa.SmallInteger(), nullable=False),
        sa.Column("peso_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rpe", sa.SmallInteger(), nullable=True),
        sa.Column(
            "dolor_lumbar",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.CheckConstraint("reps > 0", name=op.f("ck_serie_reps_positivas")),
        sa.CheckConstraint(
            "rpe IS NULL OR rpe BETWEEN 1 AND 10", name=op.f("ck_serie_rpe_rango")
        ),
        sa.CheckConstraint("series > 0", name=op.f("ck_serie_series_positivas")),
        sa.ForeignKeyConstraint(
            ["ejercicio_id"],
            ["ejercicio.id"],
            name=op.f("fk_serie_ejercicio_id_ejercicio"),
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"], ["sesion.id"], name=op.f("fk_serie_sesion_id_sesion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_serie")),
        sa.UniqueConstraint(
            "sesion_id", "orden", name=op.f("uq_serie_sesion_id_orden")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("serie")
    op.drop_table("partido")
    op.drop_index("ix_sesion_usuario_id_fecha", table_name="sesion")
    op.drop_table("sesion")
    op.drop_table("serie_plan")
    op.drop_table("sesion_plan")
    op.drop_table("comida_item")
    op.drop_table("test_intento")
    op.drop_table("receta_item")
    op.drop_table("habito_registro")
    op.drop_index("ix_comida_log_usuario_id_fecha_momento", table_name="comida_log")
    op.drop_table("comida_log")
    op.drop_table("ciclo_semana")
    op.drop_index(
        "ix_test_fisico_usuario_id_tipo_test_id_fecha", table_name="test_fisico"
    )
    op.drop_table("test_fisico")
    op.drop_table("registro_sueno")
    op.drop_table("registro_bienestar")
    op.drop_table("receta")
    op.drop_index("ix_molestia_usuario_id_zona_id_fecha", table_name="molestia")
    op.drop_table("molestia")
    op.drop_table("medida_corporal")
    op.drop_table("habito")
    op.drop_table("despensa")
    op.drop_table("ciclo")
    op.drop_table("zona_corporal")
    op.drop_table("usuario")
    op.drop_table("tipo_test")
    op.drop_table("tipo_sesion")
    op.drop_table("parametro")
    op.drop_table("ejercicio")
    op.drop_table("alimento")
    # ### end Alembic commands ###

    # Escrito a mano: autogenerate crea los tipos ENUM al crear las tablas pero
    # NO los borra en el downgrade. Sin esto, un downgrade seguido de upgrade
    # falla con «type "grupo_alimento" already exists», y la base queda con
    # ocho tipos huérfanos.
    for tipo in (
        "carga_lumbar",
        "demanda",
        "estado_ciclo",
        "estado_pesaje",
        "fase_ciclo",
        "grupo_alimento",
        "momento_comida",
        "origen_dato",
    ):
        op.execute(f"DROP TYPE {tipo}")
