"""unicidad de refresh_token_hash

Revision ID: b2dc6e2c7f8b
Revises: d6c5ddfb5112
Create Date: 2026-08-05 08:18:42.718033

"""

from collections.abc import Sequence

from alembic import op

revision: str = "b2dc6e2c7f8b"
down_revision: str | None = "d6c5ddfb5112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_auth_usuario_refresh_token_hash"),
        "auth_usuario",
        ["refresh_token_hash"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_auth_usuario_refresh_token_hash"), "auth_usuario", type_="unique"
    )
    # ### end Alembic commands ###
